# Generated by Django 4.1.2 on 2022-10-28 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ai_analysis_log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('class_num', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reqeust_timestamp', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
            ],
        ),
    ]
