# Generated by Django 4.1.2 on 2022-10-28 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_analysis_log',
            name='response_timestamp',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
