# Generated by Django 4.1.2 on 2022-10-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ai_analysis_log_response_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_analysis_log',
            old_name='reqeust_timestamp',
            new_name='request_timestamp',
        ),
    ]
