# Generated by Django 4.1.2 on 2022-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_reqeust_timestamp_ai_analysis_log_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='request_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ai_analysis_log',
            name='response_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
